# Generated by Django 5.0.3 on 2024-04-21 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseValue', models.IntegerField()),
                ('purchaseDate', models.DateTimeField()),
                ('sellValue', models.IntegerField()),
                ('sellDate', models.DateTimeField()),
                ('stockId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trade.stock')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trade.users')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFavourite', models.BooleanField()),
                ('stockId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trade.stock')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trade.users')),
            ],
        ),
    ]
